### ISSUE TITLE
Add WrongSecrets

### ISSUE THREAD

**Issue by davevs** [davevs/dvxte#5]
https://github.com/commjoen/wrongsecrets

**Comment by commjoen** [comment]
Best for now is to use https://github.com/commjoen/wrongsecrets/releases/download/1.3.2/wrongsecrets-1.3.2-SNAPSHOT.jar , but later on, you can get the newest from mvn central or somethign alike after we fixed https://github.com/commjoen/wrongsecrets/issues/178

**Comment by davevs** [comment]
working
